meta:
  app_id: inriver_connector
  display_name: inriver_connector
  version: 1.0.0-dev.2
  vendor: kraftvaerk
  summary: synchs channel catalogues from inriver
  support_url: https://kraftvaerk.com
  contact_email: teemu.eronne@kraftvaerk.com
  categories:
    - Testing & Utilities
  availability:
    - us

runtime: node22

functions:
  handle_incoming_object:
    entry_point: HandleIncomingObject
    description: Transforms incoming data into source object

jobs:
  historical_import:
    entry_point: HistoricalImport
    description: Performs a one-time historical import when triggered

  nightly_import:
    entry_point: NightlyImport
    # runs at midnight every night
    cron: 0 0 0 ? * *
    description: Performs a nightly import for data that isn't provided or needed in real-time

